export interface Penduduk {
    id: number,
    nik: string,
    no_kk: string,
    nama_lengkap: string,
    jenis_kelamin: number,
    kode_prov: string,
    kode_kab: string,
    kode_kec: string,
    kode_desa: string,
    tempat_lahir: string,
    tanggal_lahir: string,
    umur: number,
    pendidikan_terakhir: number,
    status_pekerjaan: number,
    pekerjaan: string,
    jenis_pekerjaan: number,
    status_stunting: number,
    created_by: number,
    updated_by: number,
    created_at: string,
    updated_at: string,
    nama_sls: string,
    alamat: string,
    status_pernikahan: number,
    status_dalam_bekerja: number,
    encId: string
}